"""EDITOR-region edit dating — shared between overview and staleness lints.

Hybrid wiki pages (overview·overviews/<slug>·…) carry `<!-- AUTO:* -->` blocks
regenerated by `python tools/build.py` on every build. Their churn alone must
NOT count as an authored edit. These helpers hash/diff only the EDITOR region
(AUTO blocks stripped) so that "when was this page last *authored*" tracks human
narrative changes, not AUTO rebuilds.

Both consumers need the same notion of body age:
  - overview.py  — Freshness advisory (frontmatter vs body edit date)
  - staleness.py — uses the EDITOR-body date (not frontmatter `last_updated`)
                   as the staleness baseline for derived narrative types, so a
                   partial edit that bumps `last_updated` without re-grounding
                   the body cannot mask upstream staleness.
"""
from __future__ import annotations

import hashlib
import re
import subprocess
import sys
from functools import lru_cache
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
from _lib import AUTO_BLOCK_RE, strip_frontmatter  # noqa: E402


def editor_hash(content: str) -> str:
    """SHA1 of the authored narrative — AUTO blocks AND frontmatter stripped.

    Frontmatter must be excluded or the hash is self-referential: bumping
    `last_updated` alone changes it, so the page dates itself fresh on an edit
    that never touched the narrative. That is the exact masking these helpers
    exist to prevent — a commit that only appends a `sources:` entry and bumps
    `last_updated` would otherwise register as an authored edit, hiding a body
    months older than its upstream. `strip_frontmatter` is a no-op on the root
    meta files, which carry none.
    """
    editor = AUTO_BLOCK_RE.sub("", strip_frontmatter(content))
    return hashlib.sha1(editor.encode("utf-8", errors="replace")).hexdigest()


def git_head_text(path: Path) -> str | None:
    """`git show HEAD:<path>` content (utf-8, cp949-safe bytes decode), or None
    if `path` is new/removed in HEAD or git is unavailable. Resolves `path` to
    repo-relative first (via `_git_repo_rel`) — `git show HEAD:<abs-path>`
    silently fails, and every real caller passes an absolute WIKI path."""
    rr = _git_repo_rel(path)
    if rr is None:
        return None
    toplevel, rel = rr
    try:
        r = subprocess.run(
            ["git", "-C", toplevel, "show", f"HEAD:{rel}"],
            capture_output=True, timeout=5, check=False,
        )
        if r.returncode != 0:
            return None
        # Normalize CRLF→LF so a CRLF HEAD blob hashes identically to the
        # universal-newline reads it gets compared against (_hash_at, read_text).
        return (r.stdout or b"").decode("utf-8", errors="replace").replace("\r\n", "\n")
    except (subprocess.SubprocessError, FileNotFoundError, OSError):
        return None


def last_commit_date(path: Path) -> str | None:
    """YYYY-MM-DD of the most recent commit touching `path`, or None if git is
    unavailable or the file is untracked. Resolves via `_git_repo_rel` so the
    result is independent of the caller's cwd (like the other helpers here)."""
    rr = _git_repo_rel(path)
    if rr is None:
        return None
    toplevel, rel = rr
    try:
        r = subprocess.run(
            ["git", "-C", toplevel, "log", "-1", "--format=%cs", "--", rel],
            capture_output=True, text=True, timeout=5, check=False,
            encoding="utf-8", errors="replace",
        )
        if r.returncode != 0:
            return None
        out = r.stdout.strip()
        return out if re.match(r"^\d{4}-\d{2}-\d{2}$", out) else None
    except (subprocess.SubprocessError, FileNotFoundError, OSError):
        return None


def _git_repo_rel(path: Path) -> tuple[str, str] | None:
    """(repo toplevel, repo-relative posix path) for `path`, or None.

    `git show <hash>:<p>` requires `p` to be REPO-RELATIVE — an absolute path
    after the colon silently fails (returns nothing), which would make every
    per-commit hash lookup miss and fall through to the oldest commit date.
    Resolve both via the file's own directory so the result is independent of
    the caller's cwd or whether it passed an absolute or relative path."""
    toplevel = _git_toplevel(str(path.parent))
    if toplevel is None:
        return None
    try:
        rel = path.resolve().relative_to(Path(toplevel).resolve()).as_posix()
    except (OSError, ValueError):
        return None
    return toplevel, rel


@lru_cache(maxsize=None)
def _git_toplevel(directory: str) -> str | None:
    """Repo toplevel containing `directory`, or None. Cached — every path in a
    lint run resolves to the same handful of directories, and the `rev-parse`
    spawn costs more than the `git show` it precedes."""
    try:
        top = subprocess.run(
            ["git", "-C", directory, "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, timeout=5, check=False,
            encoding="utf-8", errors="replace",
        )
        if top.returncode != 0 or not top.stdout.strip():
            return None
        return top.stdout.strip()
    except (subprocess.SubprocessError, FileNotFoundError, OSError):
        return None


def editor_last_commit_date(path: Path) -> str | None:
    """YYYY-MM-DD of the most recent commit that actually changed the file's
    EDITOR region (AUTO-block rebuilds excluded).

    Walks `git log` newest→oldest and diffs each commit's EDITOR-hash against
    its parent. First commit where the hash differs = last EDITOR-material
    change. If the whole history shares one EDITOR hash (only AUTO rewrites on
    top of an initial author commit), the oldest commit date is returned.
    Returns None when git is unavailable or the file has no history.
    """
    rr = _git_repo_rel(path)
    if rr is None:
        return None
    toplevel, rel = rr
    try:
        log = subprocess.run(
            ["git", "-C", toplevel, "log", "--format=%H %cs", "--", rel],
            capture_output=True, text=True, timeout=10, check=False,
            encoding="utf-8", errors="replace",
        )
        if log.returncode != 0 or not log.stdout.strip():
            return None
    except (subprocess.SubprocessError, FileNotFoundError, OSError):
        return None

    commits: list[tuple[str, str]] = []
    for line in log.stdout.strip().splitlines():
        parts = line.split(" ", 1)
        if len(parts) == 2 and re.match(r"^\d{4}-\d{2}-\d{2}$", parts[1]):
            commits.append((parts[0], parts[1]))
    if not commits:
        return None

    def _hash_at(commit_hash: str) -> str | None:
        try:
            r = subprocess.run(
                ["git", "-C", toplevel, "show", f"{commit_hash}:{rel}"],
                capture_output=True, text=True, timeout=5, check=False,
                encoding="utf-8", errors="replace",
            )
            if r.returncode != 0:
                return None
            return editor_hash(r.stdout)
        except (subprocess.SubprocessError, FileNotFoundError, OSError):
            return None

    # Walk newest→oldest comparing each commit's EDITOR hash with the next.
    # The older hash carries into the next round as the current one, so each
    # commit is shown once rather than twice.
    current_h = _hash_at(commits[0][0])
    for i in range(len(commits) - 1):
        older_h = _hash_at(commits[i + 1][0])
        if current_h is not None and older_h is not None and current_h != older_h:
            return commits[i][1]
        current_h = older_h
    # Whole history has a single EDITOR hash — oldest commit introduced it.
    return commits[-1][1]
