"""Landscape axis lint — `wiki/overviews/<cluster>.md` (L2-3) + `wiki/overview.md` (L2-4).

Extracted from the former `content_schema.py` monolith during the lint
group refactor (2026-04-19). This module owns every check and mutation
against landscape-axis overview files:

  * completeness — every cluster slug in `graph/_clusters.json` has a
                   matching overview file (skeleton auto-generated by --fix)
  * schema       — required frontmatter + required H2 sections + AUTO
                   marker presence; adjacency section alias rule
  * metrics      — advisory Rubric indicators for the Cluster Overview
                   Evaluation Rubric (W1·W2·W3·X2 for L2-3;
                   W1·W2·W3·D1·D2·D3·F1 for L2-4)
  * freshness    — `last_updated` frontmatter vs git commit state

--fix mode does two mechanical things (skeleton creation + AUTO marker
migration) and then emits a "Claude rewrite instruction block" that
hands off EDITOR authoring to Claude via the overview Authoring Guide
(`.claude/layers/overview.md`) + Rubric
(`.claude/layers/overview.md`). The script never edits EDITOR
content itself — that boundary is enforced by the dual-automation model.

Axis pairing: the conflict axis equivalent lives in `contradiction.py`.
"""
from __future__ import annotations

import importlib.util
import json
import re
import subprocess
import sys
from datetime import date as _date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
from _lib import CLUSTER_LABELS_JSON, CLUSTERS_JSON, WIKI, WIKILINK_ANY_RE, WIKILINK_RE as _LIB_WIKILINK_RE, WIKILINK_TARGET_RE, atomic_write_text, confirm_changes, korean_mode, parse_frontmatter, print_delete_cleanup_advisory, read_text_cached, safe_slug_path, slug_only, strip_frontmatter  # noqa: E402

sys.path.insert(0, str(Path(__file__).parent))
from _advisory_common import mark  # noqa: E402
from _manifest_counts import counts as _roster_counts, threshold_label  # noqa: E402
from _editor_date import AUTO_BLOCK_RE, editor_hash as _editor_hash, editor_last_commit_date as _editor_last_commit_date, git_head_text  # noqa: E402

from _schema_common import (  # noqa: E402
    check_auto_markers,
    check_frontmatter,
    check_sections,
    migrate_markers,
)

OVERVIEWS_DIR = WIKI / "overviews"
CONTRADICTIONS_DIR = WIKI / "contradictions"
OVERVIEW_MD_PATH = WIKI / "overview.md"

# Anchor invasion thresholds — count of EDITOR narrative refs to other
# clusters' anchor_members (excluding `## Adjacent Domains & Scope` section).
# Catches the case where a cluster has been narrowed/split by re-clustering
# but EDITOR still describes the OLD broader cluster's hubs.
INVASION_REVIEW_MIN = 3   # ≥ this count → 🟡 review advisory
INVASION_REWRITE_MIN = 5  # ≥ this count → 🔴 rewrite advisory

L24_D3_MAX_RATIO = 3.0

# Readable-prose bloat advisory (Wikipedia:Article size applied — summary-style split signal).
# Measured: readable prose character count in the EDITOR region (excluding
# frontmatter·AUTO), keeping only wikilink display text and stripping markdown
# symbols·whitespace. Shared L2-3·L2-4 threshold. Calibrated 2026-06-13 — at the
# time 6 clusters 8.2k~12.0k·root 11.1k → currently no false positives + headroom.
# 🟡 review / 🔴 split recommendation. The split direction is to spin detail out
# into hubs and keep the overview as summary + drill-down only (Summary style).
SIZE_REVIEW_CHARS = 14000
SIZE_SPLIT_CHARS = 18000

OVERVIEW_REQUIRED_FRONTMATTER = {"title", "type", "cluster", "last_updated"}
OVERVIEW_REQUIRED_SECTIONS = ("## Overview", "## Recent Changes", "## Key Entities & Concepts", "## Subtopics", "## Key Trends & Figures", "## Adjacent Domains & Scope")

# `## Recent Changes` recency guard — newest date in the section must stay fresh.
# A timely section embedded in an evergreen page rots if not tended, so this
# advisory flags when the most recent dated item is older than the recommended
# window (≈3 months). Advisory only — exit code unaffected. SoT threshold.
RECENCY_STALE_DAYS = 90
OVERVIEW_AUTO_MARKERS = ("MEMBERS", "SOURCES")

LEAD_SECTION_HEADING = "## Overview"

# ── Phase 1: craft skill (encyclopedia-writing) orchestration ──
# The enc.link-density(legacy W1)·enc.first-mention(legacy W3) measurement logic
# was moved into the skill's checks.py. overview.py is a thin orchestrator that
# injects thresholds·algorithm params from the manifest and calls the skill. The
# dual prose/code threshold is gone — the manifest is the single SoT.
_REPO_ROOT = Path(__file__).resolve().parents[2]
_ENC_CHECKS_PATH = _REPO_ROOT / ".claude" / "skills" / "encyclopedia-writing" / "checks.py"
_enc_spec = importlib.util.spec_from_file_location("enc_checks", _ENC_CHECKS_PATH)
enc_skill = importlib.util.module_from_spec(_enc_spec)
_enc_spec.loader.exec_module(enc_skill)

_MANIFEST = json.loads(
    (_REPO_ROOT / ".claude" / "layers" / "_manifest.json").read_text(encoding="utf-8")
)
_L23 = _MANIFEST["overview-cluster"]["checks"]
W1_MIN_LINKS = _L23["enc.link-density"]["threshold"]            # manifest-injected(=150)
_W1_PARAMS = _L23["enc.link-density"]["params"]
_W3_THRESHOLD = _L23["enc.first-mention"]["threshold"]          # =0
_W3_PARAMS = _L23["enc.first-mention"]["params"]

_L24 = _MANIFEST["overview-aggregate"]["checks"]
L24_W1_MIN_LINKS = _L24["enc.link-density"]["threshold"]        # manifest-injected(=200)
_L24_W1_PARAMS = _L24["enc.link-density"]["params"]
_L24_W3_THRESHOLD = _L24["enc.first-mention"]["threshold"]      # =0
_L24_W3_PARAMS = _L24["enc.first-mention"]["params"]

# L2-4 aggregate D-series measurement — con(D1 MECE)·enc(D2 drill·F1 coatrack)·jrn(D3 balance).
def _load_skill(name, alias):
    spec = importlib.util.spec_from_file_location(alias, _REPO_ROOT / ".claude" / "skills" / name / "checks.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod
con_skill = _load_skill("consulting-writing", "con_checks_ov")
jrn_skill = _load_skill("journalism-writing", "jrn_checks_ov")
# The cit G1·G2 schema meta-use measurement is owned by the scholarly-citation
# skill (moved from legacy _contradiction_meta_patterns). The threshold VALUE is
# manifest-checks-injected.
cit_skill = _load_skill("scholarly-citation", "cit_checks_ov")
_G1_THRESHOLD = _L23["cit.grade-meta"]["threshold"]            # =2
_G2_THRESHOLD = _L23["cit.cite-type-meta"]["threshold"]        # =1
_L24_G1_THRESHOLD = _L24["cit.grade-meta"]["threshold"]        # =2
_L24_G2_THRESHOLD = _L24["cit.cite-type-meta"]["threshold"]    # =1
# Encyclopedic-notation craft(B1·L1·L3)→enc · numeric density(R2)→con measurement
# moved out. Thresholds·algorithm params are manifest-injected (same value for
# cluster·aggregate). R1·L2·S6 remain house-style.
_B1_VERDICT_MAX = _L23["enc.verdict-restraint"]["threshold"]            # =2
_L1_VIOL_MAX = _L23["enc.slug-alias"]["threshold"]                      # =0
_L1_MIN_LEN = _L23["enc.slug-alias"]["params"]["min_len"]              # =10
_L3_ABBR_MAX = _L23["enc.abbr-gloss"]["threshold"]                      # =3
_R2_VIOL_MAX = _L23["con.numeric-density"]["threshold"]                # =0
_R2_MAX_PARA = _L23["con.numeric-density"]["params"]["max_per_para"]   # =5
_AGG = _MANIFEST["overview-aggregate"]["bundles"]
_AGG_CON_FN = _AGG["consulting-writing"]["fn"]
_AGG_ENC_FN = _AGG["encyclopedia-writing"]["fn"]
_AGG_JRN_FN = _AGG["journalism-writing"]["fn"]

WIKILINK_RE = WIKILINK_TARGET_RE  # capture target (including #anchor) — normalized via split("#") at the comparison site


def _paragraph_count(text: str) -> int:
    """Count of blank-line-separated paragraphs (min 1) — the denominator for W2 lead/body density. Shared L2-3·L2-4."""
    paras = [p for p in re.split(r"\n\s*\n", text) if p.strip()]
    return max(1, len(paras))

# R1 (key figure·example repetition) — advisory when the same number+unit token
# appears ≥3 times across the document. Date fragments (YYYY·YYYY-MM-DD·YYYY년 M월)
# are masked beforehand since they are editorially meaningless repetition.
# English magnitude/unit vocabulary is the native default; the Korean counter
# set (and Korean date masking) fires only under WIKI_LANG=ko (korean_mode()).
_DATE_YMD_RE = re.compile(r"\b\d{4}(?:[-./]\d{1,2}(?:[-./]\d{1,2})?)?\b")
_DATE_KO_RE = re.compile(r"\d{4}\s*년(?:\s*\d{1,2}\s*월(?:\s*\d{1,2}\s*일)?)?")
# A unit needs a lookahead wherever `\b` does not already supply one, or the token
# boundary lands mid-phrase and R1 counts a figure the body never states: `50%+1`
# yields a bare `50%`, and in Korean `2분기` yields `2분`. The word units are closed
# by `\b`; `%` and `분` are not, so those two carry explicit lookaheads below.
# `대` is dropped from the Korean roster rather than bounded — "N대 <collective noun>"
# (`5대 은행`) dominates real usage, so any boundary still mis-slices it; a genuinely
# repeated `N대` figure falls to the desk, which R1 being advisory makes affordable.
_NUM_UNIT_EN_RE = re.compile(
    r"\d+(?:[,.]\d+)*\s*(?:%(?![+\d])|(?:GB|TB|PB|GW|MW|million|billion|trillion|percent|points|tokens|parameters|users|models|employees|downloads)\b)"
)
_NUM_UNIT_KO_RE = re.compile(
    r"\d+(?:[,.]\d+)*\s*조\s*\d+(?:[,.]\d+)*\s*억"          # compound amount as one token
    r"|\d+(?:[,.]\d+)*\s*분(?![가-힣])"                      # blocks `분기`·`분야` mis-splits
    r"|\d+(?:[,.]\d+)*\s*%(?![+\d])"                         # blocks the `50%+1` phrase
    r"|\d+(?:[,.]\d+)*\s*(?:조|억|천만|백만|만|GB|TB|PB|건|명|장|배|개월|개|호|층|년|번째|주|시간)"
)

def _r1_hot_tokens(content: str) -> list[tuple[str, int]]:
    """Return numeric+unit tokens appearing ≥3 times outside dates and wikilinks."""
    clean = _DATE_YMD_RE.sub(" ", content)
    if korean_mode():
        clean = _DATE_KO_RE.sub(" ", clean)
    clean = WIKILINK_ANY_RE.sub(" ", clean)  # drop wikilink targets (cluster slugs carry digits)
    num_unit_re = _NUM_UNIT_KO_RE if korean_mode() else _NUM_UNIT_EN_RE
    counts: dict[str, int] = {}
    for m in num_unit_re.finditer(clean):
        tok = re.sub(r"\s+", " ", m.group(0).strip())
        counts[tok] = counts.get(tok, 0) + 1
    return sorted([(t, n) for t, n in counts.items() if n >= 3], key=lambda x: (-x[1], x[0]))


# R2 numeric-density(con)·B1 verdict-restraint(enc)·L1 slug-alias(enc)·L3 abbr-gloss(enc)
# measurement moved into the owning skill's checks.py (MOVE-not-COPY). R1·L2·S6 remain house-style in overview.py.


# L2 — date format standardization. Detect non-standard forms in body.
# Standard is YYYY-MM-DD / YYYY-MM only. English month-name and slash dates are
# the native default; Korean forms (YYYY년 M월 …) are flagged only under
# WIKI_LANG=ko (korean_mode()) — the gating documented in .claude/layers/overview.md.
_L2_NONSTD_EN_RE = re.compile(
    r"\b(?:January|February|March|April|May|June|July|August|September|October|November|December)"
    r"\s+\d{1,2}(?:st|nd|rd|th)?,?\s+\d{4}\b"
    r"|\b\d{4}/\d{1,2}(?:/\d{1,2})?\b"
)
_L2_NONSTD_KO_RE = re.compile(
    r"\d{4}\s*년(?:\s*\d{1,2}\s*월(?:\s*\d{1,2}\s*일)?)?"
    r"|\d{4}\s+\d{1,2}\s*월"
    r"|\d{4}\s+\d{1,2}\s*~\s*\d{1,2}\s*월"
)

def _l2_date_violations(content: str) -> list[str]:
    """Non-standard date forms (e.g. 'June 13, 2026'; YYYY년 M월 under ko). Standard is YYYY-MM-DD / YYYY-MM only."""
    # Exclude content inside code blocks / inline code
    clean = re.sub(r"```.*?```", "", content, flags=re.DOTALL)
    clean = re.sub(r"`[^`]*`", "", clean)
    hits = [m.group(0).strip() for m in _L2_NONSTD_EN_RE.finditer(clean)]
    if korean_mode():
        hits.extend(m.group(0).strip() for m in _L2_NONSTD_KO_RE.finditer(clean))
    return hits


# Wikilink → display text (alias if present, else target) — shared by the S6
# visible-length helpers and the readable-prose size counter.
_WIKILINK_DISPLAY_RE = re.compile(r"\[\[([^\]|]+\|)?([^\]]+)\]\]")


# S6 — sentence length cap. Split on sentence-ending punctuation; flag >200 chars.
def _s6_long_sentences(content: str) -> list[int]:
    """Return list of (character_length) for sentences exceeding 200 chars."""
    # Strip code blocks and wikilinks (wikilinks are single tokens to the reader)
    clean = re.sub(r"```.*?```", "", strip_frontmatter(content), flags=re.DOTALL)
    # Split into sentences by terminator (the Korean 다 terminator joins only
    # under WIKI_LANG=ko). Each newline also splits.
    term = r"(?<=[.!?다])\s+|\n+" if korean_mode() else r"(?<=[.!?])\s+|\n+"
    sentences = re.split(term, clean)
    long_ones = []
    for s in sentences:
        s = s.strip()
        # Skip headers, bullets, tables
        if not s or s.startswith("#") or s.startswith("-") or s.startswith("|") or s.startswith(">"):
            continue
        # Remove wikilinks to count just visible chars
        visible = _WIKILINK_DISPLAY_RE.sub(r"\2", s)
        visible = re.sub(r"\*\*", "", visible)
        if len(visible) > 200:
            long_ones.append(len(visible))
    return long_ones


# S6 anti-pattern — "one paragraph = one very long sentence" (overview.md "paragraph-separation principle").
# Flag paragraphs ≥ 500 visible chars with zero sentence terminators.
def _s6_paragraph_no_period(content: str) -> list[tuple[int, int]]:
    """Return list of (paragraph_index, visible_char_count) for paragraphs
    lacking any sentence terminator yet exceeding 500 visible chars."""
    clean = re.sub(r"```.*?```", "", strip_frontmatter(content), flags=re.DOTALL)
    paras = re.split(r"\n\s*\n", clean)
    violations = []
    for i, p in enumerate(paras):
        s = p.strip()
        if not s:
            continue
        # Skip header·bullet·table·blockquote single-structure paragraphs.
        non_empty = [ln for ln in s.splitlines() if ln.strip()]
        if non_empty and all(
            ln.lstrip().startswith(("#", "-", "|", ">", "*", "<!--"))
            for ln in non_empty
        ):
            continue
        visible = _WIKILINK_DISPLAY_RE.sub(r"\2", s)
        visible = re.sub(r"\*\*", "", visible)
        # The 다-terminator exemption is a Korean-corpus heuristic (WIKI_LANG=ko).
        if re.search(r"[.!?]", visible) or (korean_mode() and re.search(r"다(?=\s|$)", visible)):
            continue
        if len(visible) >= 500:
            violations.append((i, len(visible)))
    return violations
UNALIASED_WIKILINK_RE = re.compile(r"\[\[([^\]|]+)\]\]")
ADJACENCY_SECTION_RE = re.compile(
    r"## Adjacent Domains & Scope\n(.*?)(?=\n## |\n<!-- AUTO|\Z)",
    re.DOTALL,
)


def _load_clusters() -> dict | None:
    # Prereq failure returns None (→ run() exits 2 via stderr) rather than
    # raising SystemExit(str)(=exit 1): lint.py calls run() in-process, so a
    # raise would abort the whole `lint all` before the remaining groups and
    # the summary. Mirrors synthesis.py's stderr + return 2 convention.
    if not CLUSTERS_JSON.exists():
        print(
            f"ERROR: {CLUSTERS_JSON} not found. Run `python tools/build.py clusters` first.",
            file=sys.stderr,
        )
        return None
    return json.loads(CLUSTERS_JSON.read_text(encoding="utf-8"))


def _check_adjacency_aliases(content: str, cluster_slugs: set[str], path: Path) -> list[str]:
    """Detect cluster-slug wikilinks missing a display-name alias in the
    `## Adjacent Domains & Scope` section."""
    m = ADJACENCY_SECTION_RE.search(content)
    if not m:
        return []
    issues: list[str] = []
    for target in UNALIASED_WIKILINK_RE.findall(m.group(1)):
        slug = target.strip()
        if slug in cluster_slugs:
            issues.append(
                f"  {path.name}: `## Adjacent Domains & Scope` has un-aliased cluster link "
                f"`[[{slug}]]` — use `[[{slug}|<cluster name>]]`"
            )
    return issues


def _fix_adjacency_aliases(path: Path, cluster_slug_to_name: dict[str, str]) -> list[str]:
    """Rewrite un-aliased `[[<cluster-slug>]]` inside the `## Adjacent Domains & Scope`
    section to `[[<slug>|<cluster name>]]`. The cluster name mapping is the
    authoritative `graph/_clusters.json` clusters[].name, so this fix is
    deterministic and side-effect free outside that section.

    Returns list of slugs that were rewritten.
    """
    content = path.read_text(encoding="utf-8")
    m = ADJACENCY_SECTION_RE.search(content)
    if not m:
        return []

    section = m.group(1)
    section_start = m.start(1)
    section_end = m.end(1)

    rewritten: list[str] = []

    def _replace(link_match: "re.Match[str]") -> str:
        slug = link_match.group(1).strip()
        if slug in cluster_slug_to_name:
            rewritten.append(slug)
            return f"[[{slug}|{cluster_slug_to_name[slug]}]]"
        return link_match.group(0)

    new_section = UNALIASED_WIKILINK_RE.sub(_replace, section)
    if rewritten:
        new_content = content[:section_start] + new_section + content[section_end:]
        atomic_write_text(path, new_content)
    return rewritten


def _check_cluster_name_drift(
    path: Path,
    content: str,
    fm: dict,
    slug: str,
    cluster_by_slug: dict,
    fix: bool,
) -> tuple[list[str], int, str]:
    """Compare frontmatter `title` + body H1 against `cluster["name"]` (SoT).

    The chain `cluster_labels.json` (human-edited) → `_clusters.json::
    clusters[].name` → overview MD frontmatter `title` + body `# H1` is
    one-way: when an editor renames a cluster (e.g. anchor refinement, slug
    relabel), the MD must follow. Same SoT is already used by skeleton
    creation and adjacency alias auto-fix in this module, so auto-correction
    in `--fix` mode is consistent.

    Skipped when slug ∉ cluster_by_slug (orphan MD — handled by the
    create/delete planner above).

    Returns (issues, fixed_count, new_content). `new_content` reflects any
    --fix rewrites; caller writes back if fixed_count > 0.
    """
    if slug not in cluster_by_slug:
        return [], 0, content
    expected_name = (cluster_by_slug[slug].get("name") or "").strip()
    if not expected_name:
        return [], 0, content

    issues: list[str] = []
    fixed = 0
    new_content = content

    fm_title = (fm.get("title") or "").strip()
    if fm_title and fm_title != expected_name:
        if fix:
            new_content = re.sub(
                r'^title:\s*.*$',
                lambda _m: f'title: "{expected_name}"',  # literal repl — name may hold \g/\1
                new_content,
                count=1,
                flags=re.MULTILINE,
            )
            fixed += 1
        else:
            issues.append(
                f"  {path.name}: frontmatter `title: \"{fm_title}\"` drift from "
                f"`_clusters.json::clusters[].name` `\"{expected_name}\"` — rerun --fix to sync"
            )

    h1_match = re.search(r"^# (.+?)\s*$", new_content, re.MULTILINE)
    if h1_match:
        h1_text = h1_match.group(1).strip()
        if h1_text != expected_name:
            if fix:
                new_content = re.sub(
                    r"^# .+?$",
                    lambda _m: f"# {expected_name}",  # literal repl — name may hold \g/\1
                    new_content,
                    count=1,
                    flags=re.MULTILINE,
                )
                fixed += 1
            else:
                issues.append(
                    f"  {path.name}: H1 `# {h1_text}` drift from cluster name "
                    f"`{expected_name}` — rerun --fix to sync"
                )

    return issues, fixed, new_content


def _split_sections(editor: str) -> dict[str, str]:
    """Split AUTO-stripped overview text into {`## <title>`: body} sections —
    preamble before the first H2 keyed `_preamble`; `###` subheaders stay in body."""
    sections: dict[str, str] = {}
    current = "_preamble"
    buffer: list[str] = []
    for line in editor.splitlines():
        m = re.match(r"^##\s+(.+?)\s*$", line)
        if m and not line.startswith("###"):
            if buffer:
                sections[current] = "\n".join(buffer)
            current = f"## {m.group(1).strip()}"
            buffer = []
        else:
            buffer.append(line)
    if buffer:
        sections[current] = "\n".join(buffer)
    return sections


def _link_metrics(content: str) -> dict:
    """Compute link-density metrics for Cluster Overview Evaluation Rubric."""
    editor = AUTO_BLOCK_RE.sub("", content)

    sections = _split_sections(editor)

    all_links = WIKILINK_RE.findall(editor)  # for X2 contradiction_refs (not yet moved)
    # enc.link-density(W1) measurement moved into the encyclopedia-writing skill — manifest params injected.
    total = enc_skill.count_wikilinks_in_editor_region(content, **_W1_PARAMS)

    by_section: dict[str, int] = {}
    for heading, body in sections.items():
        by_section[heading] = len(WIKILINK_RE.findall(body))

    lead_text = sections.get(LEAD_SECTION_HEADING, "")
    lead_links = len(WIKILINK_RE.findall(lead_text))
    lead_paras = _paragraph_count(lead_text) if lead_text else 1
    lead_density = lead_links / lead_paras if lead_paras else 0.0

    body_text = "\n".join(
        body for head, body in sections.items()
        if head not in (LEAD_SECTION_HEADING, "_preamble")
    )
    body_links = len(WIKILINK_RE.findall(body_text))
    body_paras = _paragraph_count(body_text) if body_text else 1
    body_density = body_links / body_paras if body_paras else 0.0

    lead_body_ratio = (lead_density / body_density) if body_density else float("inf")

    # enc.first-mention(W3) measurement moved into the encyclopedia-writing skill.
    # exempt_sections (`## Adjacent Domains & Scope` — a 2× adjacent-cluster citation
    # is normal)·strip_auto are manifest-injected.
    dup_total, duplicates = enc_skill.count_duplicate_links(content, **_W3_PARAMS)

    theme_stems: set[str] = set()
    if CONTRADICTIONS_DIR.exists():
        theme_stems = {
            p.stem for p in CONTRADICTIONS_DIR.glob("*.md")
            if not p.name.startswith("_")
        }
    contradiction_refs = 0
    for target in all_links:
        # Strip subdir prefix AND any `#anchor` (Xanadu citation anchoring) so
        # `[[contradictions/foo#section]]` resolves to the bare theme stem.
        stem = slug_only(target)
        if stem in theme_stems:
            contradiction_refs += 1

    # R1·L2·S6 are house-style (remain in overview.py). R2→con, B1·L1·L3 moved to the enc skill.
    r1_hot = _r1_hot_tokens(editor)
    r2_violations = con_skill.count_density_violations(editor, max_per_para=_R2_MAX_PARA)
    b1_hits = enc_skill.find_verdict_hits(editor)
    l1_violations = enc_skill.find_unaliased_slugs(editor, min_len=_L1_MIN_LEN)
    l2_violations = _l2_date_violations(editor)
    l3_violations = enc_skill.find_abbr_violations(editor)
    s6_long = _s6_long_sentences(editor)
    s6_para_anti = _s6_paragraph_no_period(editor)

    # G1·G2 — Phase 2 source schema meta-use (advisory, new dimension 7).
    # The body should differentiate a source's evidence grade (data/analysis/
    # forecast)·attribution strength·citation type. The Phase 2 schema attached
    # this to 1283 sources, so this auto-measures the gap where the cluster
    # overview EDITOR fails to leverage it.
    g1_grade_meta = cit_skill.count_grade_meta(editor)
    g2_cite_type_meta = cit_skill.count_cite_type_meta(editor)

    return {
        "total": total,
        "by_section": by_section,
        "lead_density": round(lead_density, 2),
        "body_density": round(body_density, 2),
        "lead_body_ratio": round(lead_body_ratio, 2) if lead_body_ratio != float("inf") else None,
        "duplicates": duplicates,
        "dup_total": dup_total,
        "contradiction_refs": contradiction_refs,
        "r1_hot": r1_hot,
        "r2_violations": r2_violations,
        "b1_hits": b1_hits,
        "l1_violations": l1_violations,
        "l2_violations": l2_violations,
        "l3_violations": l3_violations,
        "s6_long": s6_long,
        "s6_para_anti": s6_para_anti,
        "g1_grade_meta": g1_grade_meta,
        "g2_cite_type_meta": g2_cite_type_meta,
    }


def _editor_has_uncommitted(path: Path) -> bool:
    """True if working-tree EDITOR region differs from HEAD EDITOR region.

    Replaces a naive `git status --porcelain` check, which flags AUTO-only
    rebuilds as dirty and produced false Freshness warnings.
    """
    head = git_head_text(path)
    if head is None:
        return False
    try:
        current = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    return _editor_hash(current) != _editor_hash(head)




def _freshness_line(path: Path, last_updated: object) -> str | None:
    """Flag frontmatter `last_updated` that trails the file's EDITOR
    edit state. AUTO block rebuilds do not trigger warnings.

    Advisory only — never gates exit code. Silent skip when git is
    unavailable or the field is missing/malformed.
    """
    if not isinstance(last_updated, str) or not re.match(r"^\d{4}-\d{2}-\d{2}$", last_updated):
        return None

    today = _date.today().isoformat()
    if _editor_has_uncommitted(path) and last_updated < today:
        return (
            f"    [Freshness] ⚠️ last_updated={last_updated} but EDITOR region "
            f"has uncommitted edits (today={today}) — update frontmatter before commit"
        )

    commit_date = _editor_last_commit_date(path)
    if commit_date and last_updated < commit_date:
        return (
            f"    [Freshness] ⚠️ last_updated={last_updated} but EDITOR last "
            f"changed in commit on {commit_date} — frontmatter was not refreshed"
        )

    return None


# ----- AUTO drift detector (Jaccard + source delta + top-10 shift) -----
# Advisory signal for operator: when AUTO blocks drift far from their
# committed baseline, EDITOR prose may reference stale facts/members.
# Thresholds tuned 2026-04-21 from ops-reliability retrospective — keep
# them centralized here so they're discoverable/tunable.

_WIKILINK_SLUG_RE = _LIB_WIKILINK_RE
_SOURCE_TOTAL_RE = re.compile(r"(\d+)\s+total\b")

DRIFT_JACCARD_STABLE = 0.85
DRIFT_JACCARD_REWRITE = 0.70
DRIFT_SOURCE_STABLE = 0.15
DRIFT_SOURCE_REWRITE = 0.30
DRIFT_TOP10_STABLE = 2
DRIFT_TOP10_REWRITE = 6


def _extract_auto_blocks(text: str) -> dict[str, str]:
    """Return {block_name: body} for each AUTO:X block in `text`."""
    return {m.group("name"): m.group("body") for m in AUTO_BLOCK_RE.finditer(text)}


def _auto_member_slugs(members_body: str) -> set[str]:
    """All [[slug]] targets in the AUTO:MEMBERS body (entities + concepts)."""
    return {m.group(1).strip() for m in _WIKILINK_SLUG_RE.finditer(members_body)}


def _auto_source_top(sources_body: str, n: int = 10) -> list[str]:
    """Top-N [[source-slug]] in AUTO:SOURCES body, in render order."""
    slugs: list[str] = []
    for m in _WIKILINK_SLUG_RE.finditer(sources_body):
        slugs.append(m.group(1).strip())
        if len(slugs) >= n:
            break
    return slugs


def _auto_source_total(sources_body: str) -> int:
    """Parse the 'N total' count in the AUTO:SOURCES body. 0 if absent."""
    m = _SOURCE_TOTAL_RE.search(sources_body)
    return int(m.group(1)) if m else 0


def _drift_line(path: Path, current_text: str) -> str | None:
    """Compute AUTO drift metrics vs git HEAD. Advisory only — 'stable'
    tier returns None so the lint line is silent for unchanged or near-
    stable clusters.

    Metrics:
      - member_jaccard: Jaccard similarity of AUTO:MEMBERS slug sets
      - source_delta:   |new_total − old_total| / max(old_total, 1)
      - top10_new:      count of AUTO:SOURCES top-10 slugs absent from old top-10

    Tiers (threshold constants at module top):
      - stable (all under threshold)   → None       (silent)
      - drift (one metric crosses mid) → 🟡 advisory (EDITOR review recommended)
      - rewrite (one crosses upper)    → 🔴 rewrite (--fix recommended)
    """
    head_text = git_head_text(path)
    if head_text is None:
        return None  # new file — no baseline
    old_blocks = _extract_auto_blocks(head_text)
    new_blocks = _extract_auto_blocks(current_text)
    if not (old_blocks.get("MEMBERS") or old_blocks.get("SOURCES")):
        return None  # baseline has no AUTO content

    old_m = _auto_member_slugs(old_blocks.get("MEMBERS", ""))
    new_m = _auto_member_slugs(new_blocks.get("MEMBERS", ""))
    if old_m or new_m:
        union = old_m | new_m
        jaccard = len(old_m & new_m) / len(union) if union else 1.0
    else:
        jaccard = 1.0

    old_n = _auto_source_total(old_blocks.get("SOURCES", ""))
    new_n = _auto_source_total(new_blocks.get("SOURCES", ""))
    delta = abs(new_n - old_n) / max(old_n, 1)

    old_top10 = set(_auto_source_top(old_blocks.get("SOURCES", ""), 10))
    new_top10 = _auto_source_top(new_blocks.get("SOURCES", ""), 10)
    top10_new = sum(1 for s in new_top10 if s not in old_top10)

    # Tier classification — any one metric crossing promotes the tier
    if jaccard < DRIFT_JACCARD_REWRITE or delta > DRIFT_SOURCE_REWRITE or top10_new >= DRIFT_TOP10_REWRITE:
        tier_icon = "🔴"
        tier_note = f"rewrite — `/wiki-lint overview {path.stem} --fix` recommended"
    elif jaccard < DRIFT_JACCARD_STABLE or delta > DRIFT_SOURCE_STABLE or top10_new > DRIFT_TOP10_STABLE:
        tier_icon = "🟡"
        tier_note = "drift — EDITOR review recommended"
    else:
        return None  # stable tier — silent

    sign = "+" if new_n >= old_n else "-"
    delta_str = f"{sign}{delta * 100:.0f}%"
    return (
        f"    [AUTO drift] member_jaccard={jaccard:.2f}  "
        f"source_delta={delta_str} (srcs {old_n}→{new_n})  "
        f"top10_new={top10_new}  {tier_icon} {tier_note}"
    )


def _load_anchor_to_cluster() -> dict[str, str]:
    """Build {entity-or-concept stem → owning cluster slug} from
    `graph/cluster_labels.json`. Anchor membership is the strongest
    'this hub belongs to that cluster's narrative core' signal — used
    by `_anchor_invasion_line()` to detect EDITOR narrative drift."""
    if not CLUSTER_LABELS_JSON.exists():
        return {}
    try:
        data = json.loads(CLUSTER_LABELS_JSON.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}

    out: dict[str, str] = {}
    # cluster_labels.json may use either {"labels": [...]} or be a bare list.
    labels = data.get("labels", data) if isinstance(data, dict) else data
    if not isinstance(labels, list):
        return {}
    for label in labels:
        slug = label.get("slug") if isinstance(label, dict) else None
        if not slug:
            continue
        for anchor in label.get("anchor_members", []):
            # anchor format: "entities/Foo.md" or "concepts/Bar.md"
            parts = anchor.split("/", 1)
            if len(parts) != 2:
                continue
            stem = parts[1].rsplit(".", 1)[0]
            out[stem] = slug
    return out


def _load_cluster_pairs() -> dict[str, set[str]]:
    """Build {cluster slug → set of paired cluster slugs} from optional
    `paired_with` field in `graph/cluster_labels.json`.

    paired_with declares cluster pairs whose anchor cross-references in
    overview EDITOR are intentional (e.g. data infra ↔ adoption,
    banking ↔ regulation) and should not raise [Anchor invasion] noise.
    Field is optional; clusters without it are treated as having no
    paired neighbors (any foreign anchor counts as invasion candidate).

    Pairs are normalized to be symmetric — declaring `A.paired_with: [B]`
    is enough; B's invasion check also exempts A's anchors. This means
    editors only need to write the pair once on whichever side is more
    natural."""
    if not CLUSTER_LABELS_JSON.exists():
        return {}
    try:
        data = json.loads(CLUSTER_LABELS_JSON.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}

    pairs: dict[str, set[str]] = {}
    labels = data.get("labels", data) if isinstance(data, dict) else data
    if not isinstance(labels, list):
        return {}
    for label in labels:
        if not isinstance(label, dict):
            continue
        slug = label.get("slug")
        peers = label.get("paired_with", [])
        if not slug or not isinstance(peers, list):
            continue
        for peer in peers:
            if not isinstance(peer, str) or peer == slug:
                continue
            pairs.setdefault(slug, set()).add(peer)
            # Symmetric: declaring once on either side is enough.
            pairs.setdefault(peer, set()).add(slug)
    return pairs


def _anchor_invasion_line(
    content: str,
    cluster_slug: str,
    anchor_to_cluster: dict[str, str],
    cluster_pairs: dict[str, set[str]] | None = None,
) -> str | None:
    """Detect EDITOR narrative invasion by other clusters' anchor_members.

    The case this catches: a cluster has been narrowed/split by re-clustering
    (e.g. 2026-04-25 telecom 73→19 split off AIDC·SKT·LGU+ to
    `aidc-infrastructure`), AUTO blocks were rebuilt and committed (so
    `[AUTO drift]` is silent against HEAD), but EDITOR text still describes
    the OLD broader cluster's core hubs. Looks for `[[entity]]`/`[[concept]]`
    references in EDITOR sections OTHER than `## Adjacent Domains & Scope`
    (which is the structural place for adjacent-cluster references) that
    are `anchor_member` of a DIFFERENT cluster.

    Two false-positive guards:

    1. **paired_with whitelist** (cluster_labels.json) — clusters whose
       narrative is genuinely paired/complementary (data infra ↔ adoption,
       banking ↔ regulation, etc.) cross-reference each other's anchors
       legitimately. Anchors owned by paired clusters are excluded from the
       invasion count, so paired pairs don't trigger drift signals.

    2. **max-owner concentration tiering** — total invasion count is noisy
       because a wide-scope cluster (e.g. bank-it-modernization narrative
       naturally spans payment·regulation·AI) accumulates many distributed
       sub-references. The honest stale signal is **a single foreign owner
       cluster contributing many anchors** (telecom: aidc-infrastructure 7/7
       = 100% — narrative drift; cloud-native: max owner 2/9 distributed —
       legitimate cross-context). Tier is based on max-owner-count, not
       total.

    Tiers (counts: max single owner cluster's anchor invasions, after
    paired exemption):
      - < INVASION_REVIEW_MIN  → silent (legitimate cross-context)
      - INVASION_REVIEW_MIN..  → 🟡 review advisory
      - INVASION_REWRITE_MIN.. → 🔴 rewrite advisory
    """
    if not anchor_to_cluster:
        return None

    paired = (cluster_pairs or {}).get(cluster_slug, set())

    editor = AUTO_BLOCK_RE.sub("", content)

    # Parse into sections, drop the structurally exempt section.
    sections = _split_sections(editor)

    EXEMPT = {"## Adjacent Domains & Scope"}
    narrative = "\n".join(body for head, body in sections.items() if head not in EXEMPT)

    # Group invasions by owning cluster, excluding paired peers.
    invasions: dict[str, list[str]] = {}
    paired_exempt: dict[str, list[str]] = {}
    seen: set[str] = set()
    for target in WIKILINK_RE.findall(narrative):
        # Strip subdir prefix AND any `#anchor` (Xanadu citation anchoring) so
        # an anchored hub ref still matches its anchor_member stem.
        stem = slug_only(target)
        if stem in seen:
            continue
        seen.add(stem)
        owner = anchor_to_cluster.get(stem)
        if not owner or owner == cluster_slug:
            continue
        if owner in paired:
            paired_exempt.setdefault(owner, []).append(stem)
        else:
            invasions.setdefault(owner, []).append(stem)

    if not invasions:
        return None

    # Tier on max-owner count (single concentrated foreign cluster is the
    # honest stale signal; distributed sub-refs across many clusters are
    # legitimate cross-context).
    sorted_owners = sorted(invasions.items(), key=lambda kv: -len(kv[1]))
    max_owner, max_items = sorted_owners[0]
    max_count = len(max_items)
    if max_count < INVASION_REVIEW_MIN:
        return None

    total = sum(len(v) for v in invasions.values())
    if max_count >= INVASION_REWRITE_MIN:
        tier_icon = "🔴"
        tier_note = f"narrative drift — `/wiki-lint overview {cluster_slug} --fix` recommended"
    else:
        tier_icon = "🟡"
        tier_note = "narrative drift — EDITOR review recommended"

    top = sorted_owners[:2]
    summary = "; ".join(f"{owner}({len(items)})" for owner, items in top)
    paired_note = ""
    if paired_exempt:
        paired_total = sum(len(v) for v in paired_exempt.values())
        paired_summary = ", ".join(f"{p}({len(items)})" for p, items in paired_exempt.items())
        paired_note = f"  [paired-exempt: {paired_total} refs — {paired_summary}]"
    return (
        f"    [Anchor invasion] {total} foreign anchor refs in narrative "
        f"(top: {summary}){paired_note}  {tier_icon} {tier_note}"
    )


def _readable_prose_chars(content: str) -> int:
    """EDITOR readable-prose character count (excluding whitespace·markdown symbols·wikilink markers).

    An approximation of Wikipedia:Article size's 'readable prose'. The
    frontmatter·AUTO blocks are excluded (auto-generated·meta, so not subject to
    the bloat verdict). Wikilinks keep only their display text.
    """
    text = strip_frontmatter(content)
    text = AUTO_BLOCK_RE.sub("", text)
    text = _WIKILINK_DISPLAY_RE.sub(r"\2", text)  # wikilink → display text
    text = re.sub(r"[#*\-|>`]", "", text)
    text = re.sub(r"\s+", "", text)
    return len(text)


_RECENT_SECTION_RE = re.compile(
    r"## Recent Changes\n(.*?)(?=\n## |\n<!-- AUTO|\Z)", re.DOTALL
)
_DATE_IN_TEXT_RE = re.compile(r"\b(\d{4})-(\d{1,2})(?:-(\d{1,2}))?\b")


def _recency_line(content: str, indent: str = "    ") -> str | None:
    """`## Recent Changes` recency advisory. 🟡 when the section's newest date exceeds RECENCY_STALE_DAYS.

    A timely section embedded in an evergreen page rots if left untended, so when
    the most recent dated item is older than the recommended window (≈3 months),
    an update is recommended. Silent when there is no date (pre-authoring stage).
    No effect on exit code.
    """
    m = _RECENT_SECTION_RE.search(content)
    if not m:
        return None
    dates: list[_date] = []
    for y, mo, d in _DATE_IN_TEXT_RE.findall(m.group(1)):
        try:
            dates.append(_date(int(y), int(mo), int(d) if d else 1))
        except ValueError:
            continue
    if not dates:
        return None
    newest = max(dates)
    age = (_date.today() - newest).days
    if age > RECENCY_STALE_DAYS:
        return (
            f"{indent}[Recency] '## Recent Changes' newest item {newest.isoformat()} "
            f"({age} days ago) 🟡 — no update in {RECENCY_STALE_DAYS}+ days, consider reflecting new events"
        )
    return None


def _size_line(content: str, indent: str = "    ") -> str | None:
    """One-line readable-prose bloat advisory. None (silent) when below threshold.

    The split direction is to spin detail out into hubs and keep the overview as
    summary + drill-down only (Wikipedia:Summary style). No effect on exit code —
    a change-magnitude monitoring layer.
    """
    n = _readable_prose_chars(content)
    if n >= SIZE_SPLIT_CHARS:
        return (
            f"{indent}[Size] readable_prose={n} chars (≥{SIZE_SPLIT_CHARS}) 🔴 split — "
            f"spin detail out into hubs and keep summary + drill-down only (Summary style)"
        )
    if n >= SIZE_REVIEW_CHARS:
        return (
            f"{indent}[Size] readable_prose={n} chars (≥{SIZE_REVIEW_CHARS}) 🟡 review — "
            f"watch the bloat; consider moving detail out to hubs"
        )
    return None


def _format_metrics_line(m: dict) -> list[str]:
    """Render Rubric metrics as advisory lines for lint output."""
    w1 = mark(m["total"] >= W1_MIN_LINKS)
    # An unmeasurable body (ratio=inf → serialized as None) is a PASS — the same
    # verdict as the L2-4 path (inf >= 1.0). An empty body itself is caught
    # separately by the W1·section checks.
    w2_ok = m["lead_body_ratio"] is None or m["lead_body_ratio"] >= 1.0
    w2 = mark(w2_ok)
    w3 = mark(m["dup_total"] <= _W3_THRESHOLD)
    x2 = mark(m["contradiction_refs"] > 0)
    r1 = mark(not m["r1_hot"])
    r2 = mark(len(m["r2_violations"]) <= _R2_VIOL_MAX)
    b1 = mark(len(m["b1_hits"]) <= _B1_VERDICT_MAX)
    l1 = mark(len(m["l1_violations"]) <= _L1_VIOL_MAX)
    l2 = mark(len(m["l2_violations"]) <= 3)
    l3 = mark(len(m["l3_violations"]) <= _L3_ABBR_MAX)
    s6 = mark(len(m["s6_long"]) <= 3)
    s6_pa = mark(len(m["s6_para_anti"]) == 0)
    # G1·G2 — Phase 2 source schema meta-use (advisory, dimension 7).
    g1 = mark(m["g1_grade_meta"] >= _G1_THRESHOLD)
    g2 = mark(m["g2_cite_type_meta"] >= _G2_THRESHOLD)

    ratio_str = f"{m['lead_body_ratio']:.2f}" if m["lead_body_ratio"] is not None else "n/a"
    lines = [
        f"    [Rubric] W1 links={m['total']} (≥{W1_MIN_LINKS}) {w1}  "
        f"W2 lead/body={m['lead_density']}/{m['body_density']} ratio={ratio_str} {w2}  "
        f"W3 dup={m['dup_total']} {w3}  "
        f"X2 contradiction_refs={m['contradiction_refs']} {x2}",
        f"    [Rubric] R1 hot={len(m['r1_hot'])} {r1}  "
        f"R2 dense_paras={len(m['r2_violations'])} {r2}  "
        f"B1 verdicts={len(m['b1_hits'])} {b1}  "
        f"L1 raw_slugs={len(m['l1_violations'])} {l1}",
        f"    [Rubric] L2 date_nonstd={len(m['l2_violations'])} {l2}  "
        f"L3 abbr_unexplained={len(m['l3_violations'])} {l3}  "
        f"S6 long_sents={len(m['s6_long'])} {s6}  "
        f"S6 para_anti={len(m['s6_para_anti'])} {s6_pa}",
        f"    [Rubric] G1 grade_meta={m['g1_grade_meta']} {g1}  "
        f"G2 cite_type_meta={m['g2_cite_type_meta']} {g2}",
    ]
    if m["duplicates"]:
        top = sorted(m["duplicates"], key=lambda x: -x[1])[:3]
        dup_str = ", ".join(f"{stem}×{n}" for stem, n in top)
        lines.append(f"    [Rubric] W3 top duplicates: {dup_str}")
    if m["r1_hot"]:
        top = m["r1_hot"][:3]
        tok_str = ", ".join(f"{t}×{n}" for t, n in top)
        lines.append(f"    [Rubric] R1 top hot tokens: {tok_str}")
    if m["l1_violations"]:
        top = list(dict.fromkeys(m["l1_violations"]))[:3]
        lines.append(f"    [Rubric] L1 raw slugs: {', '.join(top)}")
    if m["l3_violations"]:
        top = m["l3_violations"][:5]
        lines.append(f"    [Rubric] L3 unexplained: {', '.join(top)}")
    return lines


def _skeleton_overview(cluster: dict) -> str:
    """New-file template for wiki/overviews/<slug>.md (when missing)."""
    today = _date.today().isoformat()
    return (
        f"---\n"
        f"title: \"{cluster['name']}\"\n"
        f"type: overview\n"
        f"tags: []\n"
        f"cluster: {cluster['slug']}\n"
        f"sources: []\n"
        f"last_updated: {today}\n"
        f"---\n\n"
        f"# {cluster['name']}\n\n"
        f"## Overview\n\n"
        f"_TODO: What this domain is and why it matters, plus the scope accumulated in the wiki, in 2–4 paragraphs._\n\n"
        f"## Recent Changes\n\n"
        f"_TODO: New events from the past ~3 months as 3–5 bullets with explicit dates (YYYY-MM[-DD]), in reverse chronological order (newest on top). "
        f"This is the timeliness channel surfaced from the evergreen body — one line per bullet, one wikilink to a key hub._\n\n"
        f"## Key Entities & Concepts\n\n"
        f"_TODO: Reference the top members in the AUTO:MEMBERS block and describe them with a summary of their role·position._\n\n"
        f"## Subtopics\n\n"
        f"_TODO: A 2–4 sentence explanation per subtopic + [[wikilink]]._\n\n"
        f"## Key Trends & Figures\n\n"
        f"_TODO: Major events·figures·recent examples._\n\n"
        f"## Adjacent Domains & Scope\n\n"
        f"_TODO: Reference adjacent cluster overviews as [[<slug>|<cluster name>]] (a display-name alias is required — CLAUDE.md 'Cluster slug alias') + a one-line description of each boundary (2–4 bullets)._\n\n"
        f"<!-- AUTO:MEMBERS BEGIN -->\n"
        f"<!-- AUTO:MEMBERS END -->\n\n"
        f"<!-- AUTO:SOURCES BEGIN -->\n"
        f"<!-- AUTO:SOURCES END -->\n"
    )


def _build_cluster_map(clusters_data: dict) -> dict[str, dict]:
    seen: set[str] = set()
    out: dict[str, dict] = {}
    for c in clusters_data.get("clusters", []):
        slug = c["slug"]
        if slug in seen:
            continue
        seen.add(slug)
        out[slug] = c
    return out


def _md_overview_slugs() -> set[str]:
    if not OVERVIEWS_DIR.exists():
        return set()
    return {
        p.stem for p in OVERVIEWS_DIR.glob("*.md")
        if not p.name.startswith("_")
    }


def _plan_overview_changes(
    cluster_by_slug: dict[str, dict],
    only_slug: str | None,
) -> tuple[list[tuple[str, dict]], list[str]]:
    """Compute create+delete plan against `_clusters.json` SoT.

    creates: (slug, cluster_dict) tuples for cluster slugs that lack an MD.
    deletes: slugs whose MD exists but the slug is not in `_clusters.json`
             (orphan from a cluster rename, removed cluster, or ad-hoc MD).

    Pure planner — no filesystem mutation. Caller handles confirmation
    and execution via `_execute_overview_plan`.
    """
    json_slugs = set(cluster_by_slug.keys())
    md_slugs = _md_overview_slugs()

    if only_slug is not None:
        json_slugs &= {only_slug}
        md_slugs &= {only_slug}

    creates = [(slug, cluster_by_slug[slug]) for slug in sorted(json_slugs - md_slugs)]
    deletes = sorted(md_slugs - json_slugs)
    return creates, deletes


def _path_has_git_history(path: Path) -> bool:
    """True if `git log -- <path>` shows any prior commits.

    Detects the "cluster re-emergence" risk: an overview MD previously
    existed (authored via Cluster Overview Rubric), was deleted during a
    transient Leiden shift, and is now about to be overwritten with a
    blank skeleton — losing prior editorial content from the working tree
    until an operator thinks to run `git show <commit>:...`.

    Uses bytes capture + explicit UTF-8 decode with replacement fallback
    so Korean file names / commit messages do not crash on Windows
    cp949 default locale.
    """
    try:
        result = subprocess.run(
            ["git", "log", "--oneline", "--", str(path)],
            cwd=_REPO_ROOT,  # else git resolved the pathspec against the
            # process cwd and returned empty, silently suppressing the warning
            capture_output=True, timeout=5, check=False,
        )
        stdout = (result.stdout or b"").decode("utf-8", errors="replace")
        return bool(stdout.strip())
    except (subprocess.SubprocessError, FileNotFoundError, OSError):
        return False


def _warn_skeleton_overwrites_history(creates: list[tuple[str, dict]]) -> None:
    """Print a pre-prompt warning when skeleton creation would overwrite files
    with git history (i.e., cluster re-emergence after prior deletion).
    Called before `confirm_changes()` so operators see the risk upfront."""
    with_history = [
        slug for slug, _ in creates
        if _path_has_git_history(OVERVIEWS_DIR / f"{slug}.md")
    ]
    if not with_history:
        return
    print()
    print("⚠️  " + "=" * 70)
    print("⚠️  Found files with git history among the skeleton-creation targets")
    print("⚠️  " + "-" * 67)
    for slug in with_history:
        print(f"⚠️    - wiki/overviews/{slug}.md")
    print("⚠️  These files were authored in the past and then deleted when their cluster transiently vanished.")
    print("⚠️  Skeleton creation overwrites them with a blank template, and the existing edited content")
    print("⚠️  does not remain in the working tree (it is preserved in git history). To restore the edited content:")
    print("⚠️    git log -- wiki/overviews/<slug>.md        # check the previous commit")
    print("⚠️    git show <commit>:wiki/overviews/<slug>.md > wiki/overviews/<slug>.md")
    print("⚠️  restore it this way, then re-run --fix (a restored file is dropped from the create targets).")
    print("⚠️  " + "=" * 70)
    print()


def _execute_overview_plan(
    creates: list[tuple[str, dict]],
    deletes: list[str],
) -> int:
    """Apply a confirmed plan: create skeleton MDs + delete orphan MDs."""
    actions = 0
    if creates:
        OVERVIEWS_DIR.mkdir(parents=True, exist_ok=True)
    for slug, cluster in creates:
        path = safe_slug_path(OVERVIEWS_DIR, slug)
        atomic_write_text(path, _skeleton_overview(cluster))
        actions += 1
        print(f"  + created overviews/{slug}.md (skeleton from _clusters.json)")
    actually_deleted: list[str] = []
    for slug in deletes:
        # Same as contradiction.py: `deletes` is derived from on-disk filenames,
        # which are not guaranteed kebab-case.
        try:
            path = safe_slug_path(OVERVIEWS_DIR, slug)
        except ValueError as e:
            print(f"  ! skipped delete of overviews/{slug}.md — {e}")
            continue
        if path.exists():
            path.unlink()
            actions += 1
            actually_deleted.append(slug)
            print(f"  - deleted overviews/{slug}.md (orphan MD — slug not in _clusters.json)")
    if actually_deleted:
        print_delete_cleanup_advisory(
            actually_deleted,
            kind="overview",
            check_cluster_labels=True,
        )
    return actions


def _check_overviews(clusters_data: dict, fix: bool, only_slug: str | None = None) -> tuple[list[str], int]:
    """Per-file schema + AUTO marker + Rubric + Freshness checks.

    File-existence reconciliation (create skeletons / delete orphans) is
    handled by the planner above and orchestrated in `run()`. This
    function only inspects MDs that already exist on disk after the plan
    has been applied.
    """
    issues: list[str] = []
    fixed_marker = 0
    fixed_cluster_slug = 0
    fixed_drift = 0
    alias_fixes = 0

    cluster_by_slug = _build_cluster_map(clusters_data)
    cluster_slug_to_name = {slug: c["name"] for slug, c in cluster_by_slug.items()}
    anchor_to_cluster = _load_anchor_to_cluster()
    cluster_pairs = _load_cluster_pairs()

    metrics_reports: list[str] = []
    for path in sorted(OVERVIEWS_DIR.glob("*.md")):
        if path.name.startswith("_"):
            continue
        if only_slug is not None and path.stem != only_slug:
            continue
        content = read_text_cached(path)
        fm = parse_frontmatter(content)
        issues.extend(check_frontmatter(fm, OVERVIEW_REQUIRED_FRONTMATTER, path))
        if fm.get("type") and fm["type"] != "overview":
            issues.append(f"  {path.name}: frontmatter `type` is `{fm['type']}` — expected `overview`")
        slug = path.stem
        if fm.get("cluster") and fm["cluster"] != slug:
            old_cluster = fm["cluster"]
            corrected = False
            if fix:
                new_content = re.sub(
                    rf'(?m)^cluster:\s*{re.escape(old_cluster)}\s*$',
                    f'cluster: {slug}',
                    content,
                    count=1,
                )
                if new_content != content:
                    content = new_content
                    atomic_write_text(path, content)
                    fm["cluster"] = slug
                    fixed_cluster_slug += 1
                    corrected = True
                    print(f"  ~ overviews/{path.name}: corrected frontmatter cluster `{old_cluster}` → `{slug}`")
            if not corrected:
                issues.append(f"  {path.name}: frontmatter `cluster: {old_cluster}` mismatches filename stem `{slug}`")
        drift_issues, drift_fixed, content = _check_cluster_name_drift(
            path, content, fm, slug, cluster_by_slug, fix
        )
        issues.extend(drift_issues)
        if drift_fixed:
            atomic_write_text(path, content)
            fixed_drift += drift_fixed
            print(f"  ~ overviews/{path.name}: synced cluster name drift ({drift_fixed} field{'s' if drift_fixed > 1 else ''})")
        issues.extend(check_sections(content, OVERVIEW_REQUIRED_SECTIONS, path))

        if fix:
            rewritten = _fix_adjacency_aliases(path, cluster_slug_to_name)
            if rewritten:
                alias_fixes += len(rewritten)
                print(f"  ~ overviews/{path.name}: aliased {', '.join(rewritten)}")
                content = read_text_cached(path)
        issues.extend(_check_adjacency_aliases(content, set(cluster_by_slug.keys()), path))

        missing_markers = check_auto_markers(content, OVERVIEW_AUTO_MARKERS, path)
        if missing_markers:
            if fix:
                new_content, added = migrate_markers(content, OVERVIEW_AUTO_MARKERS)
                if added:
                    atomic_write_text(path, new_content)
                    fixed_marker += 1
                    print(f"  ~ inserted AUTO markers into overviews/{path.name}: {', '.join(added)}")
            else:
                issues.extend(missing_markers)

        m = _link_metrics(content)
        file_lines: list[str] = []
        if m["total"] >= 20:
            file_lines.extend(_format_metrics_line(m))
        freshness = _freshness_line(path, fm.get("last_updated"))
        if freshness:
            file_lines.append(freshness)
        drift = _drift_line(path, content)
        if drift:
            file_lines.append(drift)
        invasion = _anchor_invasion_line(content, path.stem, anchor_to_cluster, cluster_pairs)
        if invasion:
            file_lines.append(invasion)
        size = _size_line(content)
        if size:
            file_lines.append(size)
        recency = _recency_line(content)
        if recency:
            file_lines.append(recency)
        if file_lines:
            metrics_reports.append(f"  overviews/{path.name}:")
            metrics_reports.extend(file_lines)

    if metrics_reports:
        print("\n[Cluster Overview Rubric metrics — advisory, see .claude/layers/overview.md Part 1]")
        for line in metrics_reports:
            print(line)

    total_fixed = fixed_marker + fixed_cluster_slug + fixed_drift + alias_fixes
    if fix and total_fixed:
        print(
            f"  overviews: {fixed_marker} marker-migrated, "
            f"{alias_fixes} alias-corrected, "
            f"{fixed_cluster_slug} cluster-slug-corrected, "
            f"{fixed_drift} drift-synced"
        )
    return issues, total_fixed


def _check_overview_md(cluster_slugs: set[str]) -> tuple[list[str], list[str]]:
    """Evaluate wiki/overview.md against the L2-4 Overview Evaluation Rubric."""
    issues: list[str] = []
    metrics_lines: list[str] = []

    if not OVERVIEW_MD_PATH.exists():
        issues.append("  wiki/overview.md missing")
        return issues, metrics_lines

    content = read_text_cached(OVERVIEW_MD_PATH)

    lead_buffer: list[str] = []
    body_sections: dict[str, str] = {}
    current_section: str | None = None
    section_buffer: list[str] = []
    for line in content.splitlines():
        if line.startswith("# ") and not line.startswith("## "):
            continue
        m = re.match(r"^##\s+(.+?)\s*$", line)
        if m and not line.startswith("###"):
            if current_section is not None:
                body_sections[current_section] = "\n".join(section_buffer)
            current_section = f"## {m.group(1).strip()}"
            section_buffer = []
        else:
            if current_section is None:
                lead_buffer.append(line)
            else:
                section_buffer.append(line)
    if current_section is not None:
        body_sections[current_section] = "\n".join(section_buffer)

    lead_text = "\n".join(lead_buffer)

    all_links = WIKILINK_RE.findall(content)

    # W1 — moved to the enc.link-density skill (L2-4: raw content, strip_auto=false manifest-injected).
    w1_count = enc_skill.count_wikilinks_in_editor_region(content, **_L24_W1_PARAMS)
    w1_ok = w1_count >= L24_W1_MIN_LINKS

    # W2
    lead_links = len(WIKILINK_RE.findall(lead_text))
    lead_paras = _paragraph_count(lead_text) if lead_text.strip() else 1
    lead_density = lead_links / lead_paras if lead_paras else 0.0
    body_text = "\n".join(body_sections.values())
    body_links = len(WIKILINK_RE.findall(body_text))
    body_paras = _paragraph_count(body_text) if body_text.strip() else 1
    body_density = body_links / body_paras if body_paras else 0.0
    w2_ratio = lead_density / body_density if body_density else float("inf")
    w2_ok = w2_ratio >= 1.0

    # W3 — moved to the enc.first-mention skill (L2-4 variant: per ### subsection·
    # drill-down excluded·lead excluded·raw content). All manifest params
    # (unit·exclude_patterns·include_preamble·strip_auto) are injected.
    w3_dup_total, _ = enc_skill.count_duplicate_links(content, **_L24_W3_PARAMS)
    w3_ok = w3_dup_total <= _L24_W3_THRESHOLD

    # D1(MECE cluster completeness) → consulting-writing. section_spans is reused by D2.
    _agg_con = getattr(con_skill, _AGG_CON_FN)(content, cluster_slugs=cluster_slugs)
    d1_count = _agg_con["d1_count"]
    d1_total = _agg_con["d1_total"]
    d1_ok = _agg_con["d1_ok"]
    d1_missing = _agg_con["d1_missing"]

    # D2(drill-down)·F1(Coatrack) → encyclopedia-writing. theme_stems is wiki-global.
    theme_stems: set[str] = set()
    if CONTRADICTIONS_DIR.exists():
        theme_stems = {
            pth.stem for pth in CONTRADICTIONS_DIR.glob('*.md')
            if not pth.name.startswith('_')
        }
    _agg_enc = getattr(enc_skill, _AGG_ENC_FN)(
        content, section_spans=_agg_con["section_spans"], all_links=all_links, theme_stems=theme_stems
    )
    d2_count = _agg_enc["d2_count"]
    d2_found = _agg_enc["d2_found"]
    d2_missing = _agg_enc["d2_missing"]
    d2_ok = len(d2_missing) == 0 and d2_found > 0
    f1_count = _agg_enc["f1_count"]
    f1_ok = f1_count == 0

    # D3(cross-cluster balance·due impartiality) → journalism-writing.
    _agg_jrn = getattr(jrn_skill, _AGG_JRN_FN)(all_links=all_links, cluster_slugs=cluster_slugs)
    max_refs = _agg_jrn["max_refs"]
    min_refs = _agg_jrn["min_refs"]
    d3_ratio = _agg_jrn["d3_ratio"]
    d3_ok = d3_ratio <= L24_D3_MAX_RATIO

    if not d1_ok:
        issues.append(
            f"  wiki/overview.md: D1 FAIL — only {d1_count}/{d1_total} clusters "
            f"as `## N. [[slug|...]]` sections (missing: {d1_missing})"
        )
    if not d2_ok and d2_found > 0:
        issues.append(
            f"  wiki/overview.md: D2 FAIL — clusters without self-slug "
            f"drill-down link inside their section: {d2_missing}"
        )
    if not f1_ok:
        issues.append(
            f"  wiki/overview.md: F1 FAIL — {f1_count} theme refs found "
            f"(L2-4 forbids [[<theme>]] links per Overview Taxonomy)"
        )

    # R1·L2·S6 are house-style (remain in overview.py). R2→con, B1·L1·L3 moved to the enc skill.
    # Exclude AUTO blocks (EDITOR region only) — same handling as cluster `_link_metrics`. This
    # keeps the marker tokens (AUTO·STATS·BEGIN·END)·raw [[slug]] in AUTO:STATS/SOURCES/MEMBERS
    # from being false-flagged as L3/L1. W1·W2·W3·D-series intentionally measure raw content (see above).
    editor = AUTO_BLOCK_RE.sub("", content)
    r1_hot = _r1_hot_tokens(editor)
    r2_violations = con_skill.count_density_violations(editor, max_per_para=_R2_MAX_PARA)
    b1_hits = enc_skill.find_verdict_hits(editor)
    l1_raw = enc_skill.find_unaliased_slugs(editor, min_len=_L1_MIN_LEN)
    l2_violations = _l2_date_violations(editor)
    l3_violations = enc_skill.find_abbr_violations(editor)
    s6_long = _s6_long_sentences(editor)
    s6_para_anti = _s6_paragraph_no_period(editor)

    r1_ok = len(r1_hot) == 0
    r2_ok = len(r2_violations) <= _R2_VIOL_MAX
    b1_ok = len(b1_hits) <= _B1_VERDICT_MAX
    l1_ok = len(l1_raw) <= _L1_VIOL_MAX
    l2_ok = len(l2_violations) <= 3
    l3_ok = len(l3_violations) <= _L3_ABBR_MAX
    s6_ok = len(s6_long) <= 3
    s6_para_ok = len(s6_para_anti) == 0

    if not l1_ok:
        issues.append(
            f"  wiki/overview.md: L1 FAIL — {len(l1_raw)} raw kebab-case slugs without "
            f"Slug alias: {', '.join(list(dict.fromkeys(l1_raw))[:5])}"
            f"{'...' if len(set(l1_raw)) > 5 else ''}"
        )

    ok = mark
    metrics_lines.append("wiki/overview.md:")
    metrics_lines.append(
        f"  [Rubric L2-4] W1 links={w1_count} (≥{L24_W1_MIN_LINKS}) {ok(w1_ok)}  "
        f"W2 lead/body={lead_density:.2f}/{body_density:.2f} ratio="
        f"{'inf' if w2_ratio == float('inf') else f'{w2_ratio:.2f}'} {ok(w2_ok)}  "
        f"W3 dup={w3_dup_total} {ok(w3_ok)}"
    )
    metrics_lines.append(
        f"  [Rubric L2-4] D1 clusters={d1_count}/{d1_total} {ok(d1_ok)}  "
        f"D2 drilldowns={d2_count}/{d2_found} {ok(d2_ok)}  "
        f"D3 balance={max_refs}/{min_refs}={d3_ratio:.2f} {ok(d3_ok)}  "
        f"F1 theme_refs={f1_count} {ok(f1_ok)}"
    )
    metrics_lines.append(
        f"  [Rubric L2-4] R1 hot={len(r1_hot)} {ok(r1_ok)}  "
        f"R2 dense_paras={len(r2_violations)} {ok(r2_ok)}  "
        f"B1 verdicts={len(b1_hits)} {ok(b1_ok)}  "
        f"L1 raw_slugs={len(l1_raw)} {ok(l1_ok)}"
    )
    metrics_lines.append(
        f"  [Rubric L2-4] L2 date_nonstd={len(l2_violations)} {ok(l2_ok)}  "
        f"L3 abbr_unexplained={len(l3_violations)} {ok(l3_ok)}  "
        f"S6 long_sents={len(s6_long)} {ok(s6_ok)}  "
        f"S6 para_anti={len(s6_para_anti)} {ok(s6_para_ok)}"
    )
    # G1·G2 — Phase 2 source schema meta-use (advisory, dimension 7 aggregate).
    # Measure only the EDITOR region outside the AUTO:STATS block — the statistics
    # lines in aggregate `wiki/overview.md` are auto-refreshed by build.py and lie
    # outside the EDIT writer's responsibility (`editor` reused).
    g1_grade_meta = cit_skill.count_grade_meta(editor)
    g2_cite_type_meta = cit_skill.count_cite_type_meta(editor)
    g1_ok = g1_grade_meta >= _L24_G1_THRESHOLD
    g2_ok = g2_cite_type_meta >= _L24_G2_THRESHOLD
    metrics_lines.append(
        f"  [Rubric L2-4] G1 grade_meta={g1_grade_meta} {ok(g1_ok)}  "
        f"G2 cite_type_meta={g2_cite_type_meta} {ok(g2_ok)}"
    )
    if r1_hot:
        top = r1_hot[:3]
        metrics_lines.append(
            f"  [Rubric L2-4] R1 top hot tokens: "
            + ", ".join(f"{t}×{n}" for t, n in top)
        )
    if l1_raw:
        top = list(dict.fromkeys(l1_raw))[:3]
        metrics_lines.append(
            f"  [Rubric L2-4] L1 raw slugs: " + ", ".join(top)
        )
    if l3_violations:
        top = l3_violations[:5]
        metrics_lines.append(
            f"  [Rubric L2-4] L3 unexplained: " + ", ".join(top)
        )

    size = _size_line(content, indent="  ")
    if size:
        metrics_lines.append(size)
    recency = _recency_line(content, indent="  ")
    if recency:
        metrics_lines.append(recency)

    return issues, metrics_lines


def run(target: str | None = None, fix: bool = False, auto_yes: bool = False) -> int:
    """Entry point for `python tools/lint.py overview [<target>] [--fix [--yes]]`.

    target:
      - None        → all overview files (L2-3 * 9 + L2-4)
      - "<slug>"    → single cluster overview
      - "aggregate" → wiki/overview.md only

    fix:
      - False → diagnostics only (no prompt, no mutations)
      - True  → planned reconciliation against `_clusters.json` SoT after
                confirmation:
                  create: cluster slug without MD → skeleton from cluster name
                  delete: MD without matching cluster slug → remove orphan
                Plus non-destructive content fixes on existing files
                (alias auto-correction, AUTO marker migration) — these
                proceed without extra prompt. When a specific cluster
                target is supplied, prints the Claude rewrite instruction
                block at the end.

    auto_yes:
      - False → create/delete plan triggers `confirm_changes()` prompt;
        non-TTY callers (Claude Code Bash, CI) abort the create/delete
        portion with a hint to re-invoke with --yes.
      - True  → skip the prompt and apply the plan unconditionally.
        Use only after reviewing the planned changes upstream.
    """
    clusters_data = _load_clusters()
    if clusters_data is None:
        return 2
    cluster_slugs: set[str] = {c["slug"] for c in clusters_data.get("clusters", [])}

    if target is None:
        scope = "all"
    elif target == "aggregate":
        scope = "aggregate"
    elif target in cluster_slugs:
        scope = "cluster"
    else:
        # Target may also be an MD-only slug (orphan). Allow it through so
        # the per-target run can offer to delete it.
        md_slugs = _md_overview_slugs()
        if target in md_slugs:
            scope = "cluster"
        else:
            print(
                f"ERROR: target '{target}' is not a valid cluster slug, "
                f"existing overview MD slug, or 'aggregate'.",
                file=sys.stderr,
            )
            print(f"Valid cluster slugs: {sorted(cluster_slugs)}", file=sys.stderr)
            print(f"Valid MD slugs: {sorted(md_slugs)}", file=sys.stderr)
            return 2

    ov_issues: list[str] = []
    ov24_issues: list[str] = []
    ov24_metrics: list[str] = []

    if scope in ("all", "cluster"):
        only_slug = target if scope == "cluster" else None
        cluster_by_slug = _build_cluster_map(clusters_data)
        creates, deletes = _plan_overview_changes(cluster_by_slug, only_slug)

        if fix:
            plan = {"create": [f"overviews/{s}.md" for s, _ in creates],
                    "delete": [f"overviews/{s}.md" for s in deletes]}
            _warn_skeleton_overwrites_history(creates)
            approved = confirm_changes(
                plan,
                context="overview MD ↔ _clusters.json sync",
                auto_yes=auto_yes,
            )
            if approved:
                _execute_overview_plan(creates, deletes)
            else:
                for slug, _c in creates:
                    ov_issues.append(
                        f"  overviews/{slug}.md missing (cluster `{slug}` in "
                        f"_clusters.json) — re-run --fix and confirm, or add --yes"
                    )
                for slug in deletes:
                    ov_issues.append(
                        f"  overviews/{slug}.md exists but slug `{slug}` is not in "
                        f"_clusters.json — re-run --fix and confirm to delete, or "
                        f"rebuild graph via `python tools/build.py clusters`"
                    )
        else:
            for slug, _c in creates:
                ov_issues.append(
                    f"  overviews/{slug}.md missing (cluster `{slug}` in _clusters.json) "
                    f"— `/wiki-lint overview --fix` creates skeleton (with confirmation)"
                )
            for slug in deletes:
                ov_issues.append(
                    f"  overviews/{slug}.md exists but slug `{slug}` is not in "
                    f"_clusters.json — `/wiki-lint overview --fix` deletes orphan "
                    f"(with confirmation), or rebuild graph via "
                    f"`python tools/build.py clusters`"
                )

        schema_issues, _actions = _check_overviews(clusters_data, fix, only_slug=only_slug)
        ov_issues.extend(schema_issues)

    if scope in ("all", "aggregate"):
        ov24_issues, ov24_metrics = _check_overview_md(cluster_slugs)
        if ov24_metrics:
            print("\n[L2-4 Overview Rubric metrics — advisory, see .claude/layers/overview.md Part 2]")
            for line in ov24_metrics:
                print(line)

    if fix and scope in ("cluster", "aggregate"):
        print()
        print("=" * 72)
        print("[/wiki-lint overview --fix] Claude rewrite instruction block")
        print("=" * 72)
        if scope == "cluster":
            print(f"Target: wiki/overviews/{target}.md (L2-3 cluster overview)")
            print()
            print("Execution order (Claude):")
            print("  1. Read .claude/layers/overview.md → Part 1 (Cluster Overview)")
            print("  2. Read .claude/layers/overview.md → Part 1 Rubric (Evaluation Rubric)")
            print(f"  3. Read wiki/overviews/{target}.md (current state)")
            print("  4. Authoring Guide Part 1 → perform execution steps 1–7")
            p1 = _roster_counts("overview-cluster")
            print(f"  5. Re-run `python tools/lint.py overview {target}` → check Rubric metrics·Freshness")
            print(f"  6. Iterate until {threshold_label(p1)} is achieved")
            print("  7. When done, update frontmatter `last_updated` to today's date")
        elif scope == "aggregate":
            cluster_count = sum(
                1 for p in OVERVIEWS_DIR.glob("*.md") if not p.name.startswith("_")
            )
            print("Target: wiki/overview.md (L2-4 root overview)")
            print()
            print("Execution order (Claude):")
            print("  1. Read .claude/layers/overview.md → Part 2 (Root Overview)")
            print("  2. Read .claude/layers/overview.md → Part 2 Rubric (Evaluation Rubric)")
            print(f"  3. Read wiki/overview.md (current state) + all {cluster_count} cluster overviews")
            print("  4. Authoring Guide Part 2 → perform execution steps 1–7")
            print("  5. Re-run `python tools/lint.py overview aggregate` → check Rubric L2-4 metrics")
            p2 = _roster_counts("overview-aggregate")
            print(f"  6. Iterate until {threshold_label(p2)} is achieved")

    all_issues = ov_issues + ov24_issues
    if all_issues:
        print(f"\n[overview scope: {len(all_issues)} schema issue(s)]")
        for i in all_issues:
            print(i)
        print(
            "\nFAIL — overview scope has schema deviations. "
            "See .claude/layers/overview.md for EDITOR authoring."
        )
        return 1

    print("\nOK — overview scope: schema + L2-4 required criteria")
    return 0


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("target", nargs="?", default=None)
    ap.add_argument("--fix", action="store_true")
    ap.add_argument("--yes", "-y", action="store_true")
    args = ap.parse_args()
    sys.exit(run(target=args.target, fix=args.fix, auto_yes=args.yes))
