"""Collect + classify `## Connections` `contradicts:` lines into _contradictions.json.

Pipeline:
  1. Scan Layer 2-1 source pages only (wiki/sources/*.md), parse `## Connections`
     section for lines matching `- contradicts: [[Hub]] — desc`. Syntheses/
     trails/overviews (Layer 2-3) are deliberately out of scope — the layer
     hierarchy forbids Layer 2-2 output from pulling in Layer 2-3 analyses.
  2. Classify each claim into {real, superseded, related, soft} via
     tools/_contradiction_rules.json (regex keyword patterns, priority cascade).
     The matching score is emitted as `type_score` (0.0~1.0).
  3. Compute `evidence_strength` (0.0~1.0) per claim from Phase 2 metadata —
     anchor presence in claim wikilink, source date recency, source primary
     evidence ratio (`[fact]`/`[analysis]`/`[forecast]` distribution in `## Key Claims`),
     and target hub type (entity/concept/source).
  4. Write wiki/contradictions/_contradictions.json (enriched with
     type + type_score + evidence_strength).

Two scores are orthogonal: `type_score` reflects classification keyword
match strength (text-pattern dimension), `evidence_strength` reflects
attribution rigor of the underlying source (Phase 2 schema dimension).
Theme MD authoring uses both — high type_score + low evidence_strength
flags weasel-style classification with weak underlying evidence; low
type_score + high evidence_strength flags ambiguous classification with
strong underlying evidence (re-classification candidates).

The JSON is the Layer 2-2 programmatic raw DB. Theme-level grouping of claims
is handled at Layer 2-3 via `wiki/contradictions/_contradictions_themes.json`
(see `.claude/commands/wiki-lint-theme-mapping.md`). Hand-authored theme analyses
live in `wiki/contradictions/<theme>.md` and the Layer 2-4 aggregation in
`wiki/contradiction.md`; neither is generated by this module.

**Design — no AUTO blocks in theme MDs**: unlike landscape-axis overview files,
theme MDs are pure editorial content (frontmatter + 4 H2 sections). The raw
claim DB this module writes is consumed at authoring time via Claude's direct
JSON Reads, not mirrored into the MDs. See CLAUDE.md "Theme Contradiction
Format" for the design rationale.

Flags:
  dry_run=True  — compute + print distribution, but write nothing.

Runnable standalone: `python tools/build.py contradictions [--dry-run]`.
Runs as its own pipeline phase before index (tools/build.py PIPELINE).
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import sys
from collections import Counter
from datetime import date, datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
from _lib import GRADE_MARKER_RE, WIKI as wiki, atomic_write_if_changed, source_date_from_text  # noqa: E402

TOOLS = Path(__file__).parent.parent
RULES_PATH = TOOLS / "_contradiction_rules.json"

# Whole-line placeholder markers for an empty `contradicts:` field. Matched on
# the normalized full claim text (not substring) so a real claim that merely
# contains one of these tokens — e.g. "argues nonexistent data" (contains "none"),
# "no contradiction with X" — is not silently dropped.
SKIP_MARKERS = {
    "none", "no contradictions found", "no contradiction", "no contradictions",
    "consistency maintained",
}

TYPE_ORDER = ["real", "superseded", "related", "soft"]

# evidence_strength weights — sum 1.0
EVIDENCE_WEIGHTS = {
    "anchor": 0.30,    # Xanadu citation anchoring presence in claim wikilink
    "recency": 0.15,   # source date freshness (≤90d / ≤365d / else)
    "primary": 0.40,   # source's [fact]/[analysis]/[forecast] primary ratio
    "hub_type": 0.15,  # entity (specific) vs concept (abstract) vs source target
}

# Recency tiers (days since source date)
RECENCY_RECENT = 90
RECENCY_MID = 365

# Hub type scores — entity hubs are most concrete, concepts more abstract,
# source-to-source contradictions intermediate
HUB_TYPE_SCORE = {
    "entity": 1.0,
    "concept": 0.6,
    "source": 0.5,
    "missing": 0.0,
}

# Match the FIRST wikilink in a claim — captures (slug, anchor, alias).
# `## Connections` lines emitted by the contradicts collector follow the canonical
# format `- contradicts: [[Hub]] — desc`, so the first link in `claim_text`
# is always the contradicts target; this regex powers `_evidence_strength`'s
# anchor presence + hub_type lookup. When a claim line embeds multiple
# wikilinks (e.g. `[[A]] vs [[B]] take opposing positions`), only A is read —
# evidence_strength then reflects A only, by design.
_FIRST_WIKILINK_RE = re.compile(
    r"\[\[([^\]|#]+?)(?:#([^\]|]+?))?(?:\|([^\]]+?))?\]\]"
)

# Grade marker on `## Key Claims` claim lines (Phase 2 atomic unit prefix):
# shared GRADE_MARKER_RE from _lib (single definition with graph.py).

# `## Key Claims` section body extraction
_CLAIMS_SECTION_RE = re.compile(
    r"^## Key Claims\s*\n(.*?)(?=\n## |\Z)", re.DOTALL | re.MULTILINE
)



def _claim_id(claim: str) -> str:
    """Stable 8-char SHA1 hex of the claim text — unique id for a claim.

    Keyed on the claim text alone, never on the source path: renaming a source
    file leaves every claim inside it unchanged, so a rename must not strand the
    theme memberships (`_contradictions_themes.json`) that reference those claims.

    Editing the claim text still changes the id, and that orphaning is deliberate
    — a judgment was made about that wording, so a rewrite must be re-judged
    rather than silently inherited.

    Two sources carrying byte-identical claim text collapse to one id, which
    `_print_summary` surfaces loudly: theme coverage compares `source_count`
    against the *unique* id set.
    """
    return hashlib.sha1(claim.encode("utf-8")).hexdigest()[:8]


_CONTRADICTS_LINE_RE = re.compile(
    r"^\s*-\s*contradicts\s*:\s*(.+?)\s*$", re.MULTILINE
)


def _collect() -> list[dict]:
    """Scan only Layer 2-1 source pages for `## Connections` `contradicts:` lines.

    The layer hierarchy forbids Layer 2-2 (this module's output) from
    ingesting Layer 2-3 content, so syntheses/trails/overviews are
    deliberately out of scope — contradictions must originate in raw
    source reflections.
    """
    items: list[dict] = []
    d = wiki / "sources"
    if not d.exists():
        return items
    for f in sorted(os.listdir(d)):
        if not f.endswith(".md") or f.startswith("_"):
            continue
        fp = d / f
        content = fp.read_text(encoding="utf-8", errors="replace")
        rel = f"sources/{f}"
        # Locate `## Connections` section
        m = re.search(
            r"^## Connections\s*\n(.*?)(?=\n## |\Z)", content, re.DOTALL | re.MULTILINE
        )
        if not m:
            continue
        section = m.group(1)
        for line_m in _CONTRADICTS_LINE_RE.finditer(section):
            claim_text = line_m.group(1).strip()
            if len(claim_text) < 5 or claim_text.strip().lower().rstrip(".") in SKIP_MARKERS:
                continue
            items.append({
                "id": _claim_id(claim_text),
                "source": rel,
                "claim": claim_text,
                "status": "open",
            })
    return items


def _load_rules() -> dict:
    return json.loads(RULES_PATH.read_text(encoding="utf-8"))


def _classify(item: dict, rules: dict) -> tuple[str, float]:
    """Return (type, type_score) for a claim using regex priority cascade.

    type_score = sum of matched pattern weights (capped at 1.0). Higher score
    means more keyword density indicating the type. NOT a calibrated probability —
    measures pattern-match strength, not classifier confidence.
    """
    claim = item["claim"]
    scores: dict[str, float] = {}
    for category in rules["priority"]:
        total = 0.0
        for rule in rules["rules"].get(category, []):
            pat = rule["pattern"]
            weight = rule.get("weight", 0.5)
            max_pos = rule.get("max_pos")
            m = re.search(pat, claim, re.IGNORECASE)
            if m and (max_pos is None or m.start() < max_pos):
                total += weight
        if total > 0:
            scores[category] = min(1.0, total)

    if not scores:
        return "soft", 0.0

    for category in rules["priority"]:
        if category in scores:
            return category, round(scores[category], 2)
    return "soft", 0.0


def _build_source_metadata_cache() -> dict[str, dict]:
    """Pre-compute per-source date + primary evidence ratio.

    Reads each source MD once at build time. Returns map of source stem
    (without `.md`) → {date: ISO date string or None,
                        primary_ratio: 0.0~1.0 of [fact] grade markers in
                        `## Key Claims`, 0.0 if section absent or empty}.
    """
    cache: dict[str, dict] = {}
    src_dir = wiki / "sources"
    if not src_dir.exists():
        return cache
    for f in sorted(os.listdir(src_dir)):
        if not f.endswith(".md") or f.startswith("_"):
            continue
        path = src_dir / f
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        date_str = source_date_from_text(text) or None
        primary_ratio = 0.0
        section_m = _CLAIMS_SECTION_RE.search(text)
        if section_m:
            grades = GRADE_MARKER_RE.findall(section_m.group(1))
            if grades:
                primary = sum(1 for g in grades if g == "fact")
                primary_ratio = primary / len(grades)
        stem = f[:-3]  # strip .md
        cache[stem] = {"date": date_str, "primary_ratio": primary_ratio}
    return cache


def _hub_type(target_slug: str) -> str:
    """Resolve a wikilink target slug to its page type.

    Returns one of {entity, concept, source, missing}. Used to weight
    evidence_strength — entity targets (specific orgs/people) are more
    verifiable than concept targets (abstract topics).
    """
    if (wiki / "entities" / f"{target_slug}.md").exists():
        return "entity"
    if (wiki / "concepts" / f"{target_slug}.md").exists():
        return "concept"
    if (wiki / "sources" / f"{target_slug}.md").exists():
        return "source"
    return "missing"


def _evidence_strength(
    item: dict, source_meta: dict[str, dict], today: date
) -> float:
    """Compute evidence_strength 0.0~1.0 from Phase 2 metadata signals.

    Four weighted dimensions (weights sum to 1.0):
      - anchor (0.30):  claim wikilink has `#section` anchor → quote-grounded
      - recency (0.15): source date ≤90d (1.0) / ≤365d (0.5) / else (0.2)
      - primary (0.40): source's `## Key Claims` [fact] grade ratio (0~1)
      - hub_type (0.15): target hub category — entity (1.0) / concept (0.6) /
                         source (0.5) / missing (0.0)

    Orthogonal to `type_score` — measures attribution rigor of the
    underlying evidence, not classification keyword match strength.
    """
    claim = item["claim"]
    # A. Anchor presence (first wikilink in claim)
    first_link = _FIRST_WIKILINK_RE.search(claim)
    target_slug: str | None = None
    anchor_score = 0.0
    if first_link:
        target_slug = first_link.group(1).strip()
        anchor_score = 1.0 if first_link.group(2) else 0.0

    # B. Source recency — derive stem from "sources/<stem>.md"
    source_path = item["source"]
    source_stem = source_path[len("sources/"):] if source_path.startswith("sources/") else source_path
    if source_stem.endswith(".md"):
        source_stem = source_stem[:-3]
    src_data = source_meta.get(source_stem, {})
    recency_score = 0.2  # fallback for unknown date
    date_str = src_data.get("date")
    if date_str:
        try:
            src_date = datetime.strptime(date_str, "%Y-%m-%d").date()
            days_ago = (today - src_date).days
            if days_ago <= RECENCY_RECENT:
                recency_score = 1.0
            elif days_ago <= RECENCY_MID:
                recency_score = 0.5
            else:
                recency_score = 0.2
        except ValueError:
            pass

    # C. Source primary evidence ratio
    primary_score = src_data.get("primary_ratio", 0.0)

    # D. Hub type
    hub_type_score = (
        HUB_TYPE_SCORE.get(_hub_type(target_slug), 0.0)
        if target_slug else 0.0
    )

    strength = (
        EVIDENCE_WEIGHTS["anchor"] * anchor_score
        + EVIDENCE_WEIGHTS["recency"] * recency_score
        + EVIDENCE_WEIGHTS["primary"] * primary_score
        + EVIDENCE_WEIGHTS["hub_type"] * hub_type_score
    )
    return round(strength, 2)


def _classify_all(items: list[dict], rules: dict) -> list[dict]:
    """Add type + type_score + evidence_strength fields to each claim."""
    source_meta = _build_source_metadata_cache()
    today = date.today()
    enriched = []
    for it in items:
        t, score = _classify(it, rules)
        ev = _evidence_strength(it, source_meta, today)
        enriched.append({
            **it, "type": t, "type_score": score, "evidence_strength": ev,
        })
    return enriched


def _write_json(items: list[dict]) -> Path:
    p = wiki / "contradictions" / "_contradictions.json"
    atomic_write_if_changed(p, json.dumps(items, ensure_ascii=False, indent=2))
    return p


def _print_summary(items: list[dict]) -> None:
    counts = Counter(it["type"] for it in items)
    collided = [i for i, n in Counter(it["id"] for it in items).items() if n > 1]
    if collided:
        print(f"  ⚠️ claim id collision: {len(collided)} id(s) shared by byte-identical "
              f"claim text in different sources: {collided[:5]}\n"
              "     `lint contradiction theme` FAILs on source_count because coverage "
              "counts unique ids, not records.\n"
              "     Fix by rewording the less central claim — that re-keys it, so move "
              "its theme claim_ids entry to the new id in the same edit.")
    print(f"Contradictions: {len(items)} total -> _contradictions.json")
    for t in TYPE_ORDER:
        print(f"  {t:<11s} {counts.get(t, 0):>4d}")


def run(dry_run: bool = False) -> None:
    items = _collect()
    rules = _load_rules()
    enriched = _classify_all(items, rules)

    if dry_run:
        print("[dry-run] classification only, no files written")
        _print_summary(enriched)
        _print_samples(enriched)
        return

    _write_json(enriched)
    _print_summary(enriched)


def _print_samples(items: list[dict], per_type: int = 3) -> None:
    by_type: dict[str, list[dict]] = {}
    for it in items:
        by_type.setdefault(it["type"], []).append(it)
    print("\nSamples per type:")
    for t in TYPE_ORDER:
        bucket = by_type.get(t, [])
        if not bucket:
            continue
        print(f"  [{t}]")
        for it in bucket[:per_type]:
            src = it["source"].replace("sources/", "").replace(".md", "")
            print(f"    (type={it['type_score']} ev={it['evidence_strength']}) {src}: {it['claim'][:100]}")


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    run(dry_run=args.dry_run)
